### ISSUE TITLE
/dev/null in Windows

### ISSUE THREAD

**Issue by nossidge** [louismullie/bind-it#4]
Running Treat on Windows output an error from this line:

``` Ruby
puts sect.do(:chunk, :segment, :tokenize, :parse)
```

```
C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bind-it-0.2.7/lib/bind-it/jar_loader.rb:64:in `new': \dev\null (The system cannot find the path specified) (FileNotFoundException)
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bind-it-0.2.7/lib/bind-it/jar_loader.rb:64:in `set_java_logging'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bind-it-0.2.7/lib/bind-it/jar_loader.rb:46:in `init_rjb'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bind-it-0.2.7/lib/bind-it/jar_loader.rb:38:in `load_jar_rjb'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bind-it-0.2.7/lib/bind-it/jar_loader.rb:27:in `load'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bind-it-0.2.7/lib/bind-it/binding.rb:63:in `load_jar'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bind-it-0.2.7/lib/bind-it/binding.rb:71:in `block in load_default_jars'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bind-it-0.2.7/lib/bind-it/binding.rb:68:in `each'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bind-it-0.2.7/lib/bind-it/binding.rb:68:in `load_default_jars'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/bind-it-0.2.7/lib/bind-it/binding.rb:55:in `bind'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/stanford-core-nlp-0.5.1/lib/stanford-core-nlp.rb:125:in `bind'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/loaders/bind_it.rb:42:in `load'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/loaders/stanford.rb:8:in `load'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/workers/processors/parsers/stanford.rb:24:in `parse'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/entities/entity/delegatable.rb:66:in `call_worker'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/entities/entity/delegatable.rb:40:in `block (2 levels) in add_workers'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/entities/entity/applicable.rb:41:in `do_task'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/entities/entity/applicable.rb:49:in `block in do_task'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/entities/entity/applicable.rb:48:in `each'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/entities/entity/applicable.rb:48:in `do_task'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/entities/entity/applicable.rb:49:in `block in do_task'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/entities/entity/applicable.rb:48:in `each'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/entities/entity/applicable.rb:48:in `do_task'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/entities/entity/applicable.rb:49:in `block in do_task'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/entities/entity/applicable.rb:48:in `each'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/entities/entity/applicable.rb:48:in `do_task'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/entities/entity/applicable.rb:22:in `block in apply'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/entities/entity/applicable.rb:6:in `each'
    from C:/Ruby200-x64/lib/ruby/gems/2.0.0/gems/treat-2.0.9/lib/treat/entities/entity/applicable.rb:6:in `apply'
    from treat.rb:25:in `<main>'
```

I think this is because the Windows version of /dev/null is NIL. The following line fixed it, in jar_loader.rb between lines 60 and 61:

``` Ruby
if self.log_file == '/dev/null' and Gem.win_platform?
  self.log_file = 'NIL'
end
```

I'm still a Ruby newbie, so I didn't want to submit a pull request. There's probably a better way of doing this, but the above works for my setup.

**Comment by louismullie** [comment]
Fixed in release 2.1.0 of Treat. Thank you for your bug report.
