### ISSUE TITLE
jar_loader.rb:45:in `load': wrong argument type nil

### ISSUE THREAD

**Issue by chrislgrigg** [louismullie/bind-it#5]
Very odd issue here. I used `bind-it` to load `stanford-nlp-core` for a 48-hour hackathon and had no problems. A day later, I went to load the project and received this error:

```
/Users/username/.rvm/gems/ruby-2.1.3/gems/bind-it-0.2.7/lib/bind-it/jar_loader.rb:45:in `load': wrong argument type nil (expected String) (TypeError)
  from /Users/username/.rvm/gems/ruby-2.1.3/gems/bind-it-0.2.7/lib/bind-it/jar_loader.rb:45:in `init_rjb'
  from /Users/username/.rvm/gems/ruby-2.1.3/gems/bind-it-0.2.7/lib/bind-it/jar_loader.rb:38:in `load_jar_rjb'
  from /Users/username/.rvm/gems/ruby-2.1.3/gems/bind-it-0.2.7/lib/bind-it/jar_loader.rb:27:in `load'
  from /Users/username/.rvm/gems/ruby-2.1.3/gems/bind-it-0.2.7/lib/bind-it/binding.rb:63:in `load_jar'
  from /Users/username/.rvm/gems/ruby-2.1.3/gems/bind-it-0.2.7/lib/bind-it/binding.rb:71:in `block in load_default_jars'
  from /Users/username/.rvm/gems/ruby-2.1.3/gems/bind-it-0.2.7/lib/bind-it/binding.rb:68:in `each'
  from /Users/username/.rvm/gems/ruby-2.1.3/gems/bind-it-0.2.7/lib/bind-it/binding.rb:68:in `load_default_jars'
  from /Users/username/.rvm/gems/ruby-2.1.3/gems/bind-it-0.2.7/lib/bind-it/binding.rb:55:in `bind'
  from /Users/username/.rvm/gems/ruby-2.1.3/gems/stanford-core-nlp-0.5.1/lib/stanford-core-nlp.rb:125:in `bind'
  from /Users/username/.rvm/gems/ruby-2.1.3/gems/stanford-core-nlp-0.5.1/lib/stanford-core-nlp.rb:140:in `load'
  from ./bin/job_runner:41:in `<main>'
```

I'm pretty perplexed here. Is this an Rjb error? Tried forcing Rjb to 1.5.1, 1.4.9, 1.4.3, no change.

**Comment by chrislgrigg** [comment]
Just edited to get the line numbers back to default. I added a line that attempted to debug.

**Comment by chrislgrigg** [comment]
Ugh. Caused by someone setting `self.jvm_args` in such a way within our code that it returned `nil`.

**Comment by louismullie** [comment]
Glad that you got it working!
